config/routes.rb
Rails.application.routes.draw do
  devise_for :accounts, controllers:{registrations: 'accounts/registrations'}
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root to:"books#index"
  get 'books/cart', to: 'books#cart', as: 'cart'
  post 'books/add_to_cart', to: 'books#add_to_cart',as:'add_to_cart'
  delete 'books/remove_from_cart',to:'books#remove_from_cart',as:'remove_from_cart'
  post 'books/modify_add_cart', to: 'books#modify_add_cart',as: 'modify_add_cart'
  resources :books do
    collection do
      get :search
      get :new_release
      get :recently_update
    end
  end
  resources :categories 
  # resources :horses, only: :show do
  #   collection do
  #     get :search
  #   end
  # end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/account.rb
class Account < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  belongs_to :province
  has_many :orders
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  has_many :classifications, :dependent => :destroy
  has_many :categories,:through => :classifications
  has_many :orders,:through => :purchases
  has_many :purchases, :dependent => :destroy
  has_one_attached :image
  accepts_nested_attributes_for :classifications,allow_destroy: true
  validates :title,:author,:price,:quantity, presence: true
  validates :price,:quantity, :numericality => { :greater_than_or_equal_to => 0 }
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :classifications, :dependent => :destroy
  has_many :books ,:through => :classifications
  validates :name, presence: true
end

app/models/classification.rb
class Classification < ApplicationRecord
  belongs_to :book
  belongs_to :category
end
# 1

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :account
  has_many :books,:through => :purchases
  has_many :purchases, :dependent => :destroy
  validates :orderTime,:total,:shipAddress,:orderNum,:quantity, presence: true
  validates :total,:GST,:PST,:FST, :numericality => { :greater_than_or_equal_to => 0 }
end

app/models/province.rb
class Province < ApplicationRecord
  has_many :accounts
  validates :name,:tax,:GST,:PST,:FST, presence: true
  validates :tax,:GST,:PST,:FST, :numericality => { :greater_than_or_equal_to => 0 }
end

app/models/purchase.rb
class Purchase < ApplicationRecord
  belongs_to :book
  belongs_to :order
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :province
  has_many :orders
  validates :username,:password,:shipAddress, presence: true
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :load_categories,:current_customer,:initial_session

  private
  def current_customer
    if current_account
      @customer = current_account
    end
  end
  def load_categories
   @c = Category.all.map{ |u| [ u.name, u.id ] }
  end
  def initial_session
    session[:cart]||={}
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :load_cart
  def index
   @books = Book.all
   @books = Kaminari.paginate_array(@books).page(params[:page]).per(5)
  @categories = Category.all
  @orders = Order.all
  end
  def show
    @book = Book.find(params[:id])
  end
  def new_release
    @books = Book.all
    @books = Kaminari.paginate_array(@books).page(params[:page])
  end
  def recently_update
    @books = Book.all
    @books = Kaminari.paginate_array(@books).page(params[:page])
  end
  def load_cart
    keys = session[:cart].keys
    @cart_items = Book.find(keys)
  end
  def search
    if !params[:category_id].empty?
      @books = Book.joins(:classifications).where(classifications: { category_id: params[:category_id] }).where("title OR description LIKE ?","%#{params[:search_term]}%")
    else
      @books = Book.where("title OR description LIKE ?","%#{params[:search_term]}%")
    end
  end
  def add_to_cart
    if session[:cart]!={}
      if session[:cart].key?(user_params[:id])
        num = session[:cart][user_params[:id]]['quantity']
        session[:cart][user_params[:id]]['quantity']= (user_params[:quantity].to_i + num)
        redirect_to root_path
      else
        session[:cart][user_params[:id]] = {'quantity'=>user_params[:quantity].to_i}
        redirect_to root_path
      end
    else
      session[:cart][user_params[:id]] = {'quantity'=>user_params[:quantity].to_i}
      redirect_to root_path
    end
  end
  def modify_add_cart
    session[:cart][user_params[:id]]['quantity'] = user_params[:quantity].to_i
    redirect_to root_path
  end
  def remove_from_cart()
    session[:cart] = session[:cart].without(user_params[:id].to_s)
    redirect_to root_path
  end
  def user_params
    params.permit(:id,:quantity)
  end
  private
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
  end

  def show
    @c = Category.all.map{ |u| [ u.name, u.id ] }
    @category = Category.find(params[:id])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @books = Book.order(:title)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @user = User.all
  end
  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "Welcome to the app!"
      redirect_to @user
    else
      render 'new'
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/_about.html.erb
<h1>About my page!</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Final</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css">
  </head>
  <body>
  
  <%= render 'shared/navbar'%>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/shared/_cart.html.erb
<p>
cart
</p>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand text-decoration-none" href="/" >Book Shop</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                 <%if account_signed_in?%>
                     <li class="nav-item">
                   <%= link_to 'Sign out', destroy_account_session_path,method: :delete,class:'text-decoration-none px-2'%>
                      </li>
                      <li class="nav-item">
                          <%= link_to 'Edit Account', edit_account_registration_path,class:'text-decoration-none px-2'%>
                      </li>
                        <li class="nav-item">
                         <%= link_to 'My Cart','/books/cart',class: 'text-decoration-none px-2'%>
                      </li>
                <%else%>
                      <li class="nav-item">
                        <%= link_to 'Register',new_account_registration_path,class: 'text-decoration-none px-2'%>
                      </li>
                        <li>
                          <%= link_to 'Sign in', new_account_session_path,class: 'text-decoration-none px-2'%>
                        </li class="nav-item">
                <%end%>
      </ul>
      <div class="d-flex">
        <%= render partial: 'shared/search_form'%>
      </div>
    </div>
  </div>
</nav>

app/views/shared/_search_form.html.erb
<%= form_with(url: search_books_path, local: true, method: "get", class: 'd-flex') do %>
      <%= text_field_tag(:search_term, nil, class: 'form-control', placeholder: 'Search Book By Name') %>
      <%= select_tag(:category_id, options_for_select(@c),{ :include_blank => "select category"}) %>
      <%= submit_tag("Search", class: "btn btn-warning") %>
<% end %>