config/routes.rb
Rails.application.routes.draw do
  devise_for :accounts, controllers:{registrations: 'accounts/registrations'}
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root to:"books#index"
  get 'books/cart', to: 'books#cart', as: 'cart'
  post 'books/add_to_cart', to: 'books#add_to_cart',as:'add_to_cart'
  delete 'books/remove_from_cart',to:'books#remove_from_cart',as:'remove_from_cart'
  post 'books/modify_add_cart', to: 'books#modify_add_cart',as: 'modify_add_cart'
  resources :books do
    collection do
      get :search
      get :new_release
      get :recently_update
    end
  end
  resources :categories 
  # resources :horses, only: :show do
  #   collection do
  #     get :search
  #   end
  # end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/account.rb
class Account < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  belongs_to :province
  has_many :orders
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  has_many :classifications, :dependent => :destroy
  has_many :categories,:through => :classifications
  has_many :orders,:through => :purchases
  has_many :purchases, :dependent => :destroy
  has_one_attached :image
  accepts_nested_attributes_for :classifications,allow_destroy: true
  validates :title,:author,:price,:quantity, presence: true
  validates :price,:quantity, :numericality => { :greater_than_or_equal_to => 0 }
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :classifications, :dependent => :destroy
  has_many :books ,:through => :classifications
  validates :name, presence: true
end

app/models/classification.rb
class Classification < ApplicationRecord
  belongs_to :book
  belongs_to :category
end
# 1

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :account
  has_many :books,:through => :purchases
  has_many :purchases, :dependent => :destroy
  validates :orderTime,:total,:shipAddress,:orderNum,:quantity, presence: true
  validates :total,:GST,:PST,:FST, :numericality => { :greater_than_or_equal_to => 0 }
end

app/models/province.rb
class Province < ApplicationRecord
  has_many :accounts
  validates :name,:tax,:GST,:PST,:FST, presence: true
  validates :tax,:GST,:PST,:FST, :numericality => { :greater_than_or_equal_to => 0 }
end

app/models/purchase.rb
class Purchase < ApplicationRecord
  belongs_to :book
  belongs_to :order
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :province
  has_many :orders
  validates :username,:password,:shipAddress, presence: true
  has_secure_password
end

app/controllers/accounts/registrations_controller.rb
# frozen_string_literal: true

class Accounts::RegistrationsController < Devise::RegistrationsController
   before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  def create
    super
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:shipAddress,:province_id])
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:shipAddress,:province_id])
  end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :load_categories,:current_customer,:initial_session

  private
  def current_customer
    if current_account
      @customer = current_account
    end
  end
  def load_categories
   @c = Category.all.map{ |u| [ u.name, u.id ] }
  end
  def initial_session
    session[:cart]||={}
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :load_cart
  def index
   @books = Book.all
   @books = Kaminari.paginate_array(@books).page(params[:page]).per(5)
  @categories = Category.all
  @orders = Order.all
  end
  def show
    @book = Book.find(params[:id])
  end
  def new_release
    @books = Book.all
    @books = Kaminari.paginate_array(@books).page(params[:page])
  end
  def recently_update
    @books = Book.all
    @books = Kaminari.paginate_array(@books).page(params[:page])
  end
  def load_cart
    keys = session[:cart].keys
    @cart_items = Book.find(keys)
  end
  def search
    if !params[:category_id].empty?
      @books = Book.joins(:classifications).where(classifications: { category_id: params[:category_id] }).where("title OR description LIKE ?","%#{params[:search_term]}%")
    else
      @books = Book.where("title OR description LIKE ?","%#{params[:search_term]}%")
    end
  end
  def add_to_cart
    if session[:cart]!={}
      if session[:cart].key?(user_params[:id])
        num = session[:cart][user_params[:id]]['quantity']
        session[:cart][user_params[:id]]['quantity']= (user_params[:quantity].to_i + num)
        redirect_to root_path
      else
        session[:cart][user_params[:id]] = {'quantity'=>user_params[:quantity].to_i}
        redirect_to root_path
      end
    else
      session[:cart][user_params[:id]] = {'quantity'=>user_params[:quantity].to_i}
      redirect_to root_path
    end
  end
  def modify_add_cart
    session[:cart][user_params[:id]]['quantity'] = user_params[:quantity].to_i
    redirect_to root_path
  end
  def remove_from_cart()
    session[:cart] = session[:cart].without(user_params[:id].to_s)
    redirect_to root_path
  end
  def user_params
    params.permit(:id,:quantity)
  end
  private
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
  end

  def show
    @c = Category.all.map{ |u| [ u.name, u.id ] }
    @category = Category.find(params[:id])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @books = Book.order(:title)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @user = User.all
  end
  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "Welcome to the app!"
      redirect_to @user
    else
      render 'new'
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_book.html.erb
<div class="column">
  <div class="card">
    <div class="card-content">
      <p class="title">
        <% if show_link %>
          <%= link_to book.title, book %>
        <% else %>
          <%= book.title %>
        <% end %>
      </p>
      <p>Price:$ <%=  book.price %></p>
    </div>
    <footer class="card-footer">
      <p class="card-footer-item">
        Quantity: <br><%= book.quantity %>
      </p>
      <p class="card-footer-item">
        Description: <br><%= book.description %>
      </p>
      <p class="card-footer-item">
        author: <br><%= book.author %>
      </p>
    </footer>
  </div>
   <% if book.image.present?%>
   <div class="card-image">
   <figure class="image">
   <%= image_tag book.image%>
   </figure>
   </div>
   <%else%>
    <p>No image for this book yet!</p>
   <%end%>
</div>

app/views/books/cart.html.erb
<%= render 'shared/cart'%>
<h1>My cart</h1>

app/views/books/index.html.erb
<h1>Books</h1>
<% if @customer %>
  <%= @customer.email%>
  <%=session[:cart]%>
<% else %>
  <p>customer</p>
<% end %>

<div>
<% @categories.each do |category| %>
 <p><%=link_to category.name, category%></p> 
<% end %>
</div>
<p>Books</p>
<div>
<% @books.each do |book| %>
  <% if book.quantity != 0 %>
     <p> <%=link_to book.title,book%></p>
        <% if @cart_items.include?(book) %>
         <p>the item is in your cart</p>
          <p><%= form_with(model:@book, url: modify_add_cart_path(:quantity,:id)) do |f| %>
               <%= f.number_field :quantity,in: 1.to_i..book.quantity.to_i,:value => session[:cart][book.id.to_s]['quantity']%>
               <%= hidden_field_tag(:id, book.id) %>
               <%= f.submit "Modify" %></p>
             <% end %>
          <p><%= button_to "Remove from Cart", remove_from_cart_path, :method => "delete",params:{id:book.id}%></p>
        <% else %>
      <p><%= form_with(model:@book, url: add_to_cart_path(:quantity,:id)) do |f| %>
          <%= f.number_field :quantity%>
           <%= hidden_field_tag(:id, book.id) %>
          <%= f.submit "add" %>
          <% end %>
        <% end %></p>
    <% else %>
      <p><%=book.title%>(Sold out)</p>
    <% end %>
<% end %>
</div>
<%= paginate @books %>

app/views/books/new_release.html.erb
<div>
<h2>New Released Book</h2>
<% @books.each do |book| %>
     <% if book.created_at.to_time>(DateTime.now-3).to_time && book.updated_at.to_time>(DateTime.now-3).to_time || book.created_at.to_time>(DateTime.now-3).to_time%>
          <p><%= link_to book.title, book %>(new)</p>
    <% end %>
<% end %>
</div>
<%= paginate @books %>

app/views/books/recently_update.html.erb
<div>
<h2>Update recently</h2>

<% @books.each do |book| %>
     <% if book.updated_at.to_time>(DateTime.now-3).to_time && (DateTime.now-3).to_time >= book.created_at.to_time%>
          <p><%= link_to book.title, book %>(recently updated)</p>
    <% end %>
<% end %>
</div>
<div>
<%= paginate @books %>

app/views/books/search.html.erb
<p>
  Found <%= pluralize(@books.size, 'result') %>
  for the search term "<%= params[:search_term] %>".
</p>

<div class="search-results columns is-multiline">
  <%= render partial: 'books/book',
             collection: @books,
             locals: { show_link: false } %>
</div>

app/views/books/show.html.erb
<div class="columns">
  <%= render partial: 'book',
             object: @book,
             locals: { show_link: false } %>
</div>

app/views/categories/index.html.erb
<h1>Categories#index</h1>
<p>Find me in app/views/categories/index.html.erb</p>

app/views/categories/show.html.erb
<p>Category:
<%=@category.name%></p>

<div>
Books:
<%@category.books.each do |book|%>
  <p><%=link_to book.title,book%></p>
<%end%>
</div>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>